jobs:
- job: 'Ubuntu_1804'
  pool:
    vmImage: 'Ubuntu-18.04'

  steps:
  - template: azure-pipelines-steps.yml

- job: 'VS2017_Win2016'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - template: azure-pipelines-steps.yml

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'

  - script: npm pack
    displayName: 'npm pack'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
        '*.tgz'
        'package.json'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy npm package to staging'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: npm
    displayName: 'Publish npm artifact'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))