jobs:
- job: 'VS2017_Win2016'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: azure-pipelines-steps.yml
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
  - script: npm pack
    displayName: 'npm pack'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))